services:
  mariadb:
    image: mariadb:10.11
    container_name: mariadb_dev
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: justRoot
      MYSQL_DATABASE: ghcr
      MYSQL_USER: ghcr_user
      MYSQL_PASSWORD: nothingToSeeHere
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - dev-network

volumes:
  mariadb_data:

networks:
  dev-network:
    driver: bridge